skitch command date340 [<text>]:
	prefixes: @up
	trigger:
		if event-livechannel = "bot_muse":
			mod-translate for event-livechannel to "@update340::mods" and save {_data}
			twitch reply with "%{_data}%"
			stop
		#
		badge event-twitchperms is mod
		cooldown of 5 to event-livechannel
		mod-translate for event-livechannel to "@update340::mods" and save {_data}
		twitch reply with "%{_data}%"
		stop
