on load:
	load json file "plugins/musedash/hidden_vanilla.json" as "hidden_off"
	load json file "plugins/musedash/album_vanilla.json" as "album_off"
	load json file "plugins/musedash/album_modded.json" as "album_mod" 
	load json file "plugins/musedash/games_object.json" as "game_obj"
	
	load json file "plugins/musedash/twitch_blacklist.json" as "tw_bans"
	load json file "plugins/musedash/twitch_regul.json" as "twitch"
	

on skript unload:
	save all cached jsons
