skitch command mdmc:
	prefixes: _
	trigger:
		cooldown of 5 to event-livechannel
		set {_mdmc} to "MDMC is a community for modifying and creating custom songs for Muse Dash! If you are interested, use this Discord Invite: https://discord.gg/mdmc"
		set {_mdmc} to "MDMC is a community for modifying and creating custom songs for Muse Dash! [!] Due to my settings, I can't send links. A Mod must send ""@links"" for this."  if see-json "twitch" have key "stream:%event-livechannelid%_:links" is false
		twitch reply with "%{_mdmc}%"