import:
	ch.njol.skript.lang.Variable

effect index-vanilla in %~objects% for %~objects% %~objects% %~object% %~object% %~string%:
	parse:
		expr-1 is an instance of Variable
		continue
	trigger:
		delay effect
		set {_uid::*} to elements "uids[]" from cached json "van_album"
		set {_bpm::*} to expr-2
		set {_dif::*} to expr-3
		set {_des} to expr-4
		set {_by} to expr-5
		set {_sea} to expr-6
		set {_sea::*} to {_sea} split at " " if {_sea} is set
		#
		if size of {_dif::*} = 2:
			loop integers from min({_dif::*}) to max({_dif::*}):
				set {_get-a::*} to elements "level:%loop-value%[]" from cached json "van_album_plus"
				add {_get-a::*} to {_get-b::*}
				delete {_get-a::*}
			loop {_uid::*}:
				{_get-b::*} do not contain loop-value
				delete {_uid::%loop-index%}
			delete {_get-b::*}
		#
		if size of {_bpm::*} = 2:
			loop {_uid::*}:
				if element "beats:%loop-value%:min" from cached json "van_album_plus" >= min({_bpm::*}):
					element "beats:%loop-value%:max" from cached json "van_album_plus" <= max({_bpm::*})
					continue loop
				delete {_uid::%loop-index%}
		#
		if {_des} != "*":
			loop {_uid::*}:
				delete {_get-a::*}
				set {_get-a::*} to elements "design:%loop-value%[]" from cached json "van_album_plus"
				{_get-a::*} do not contain "%{_des}%"
				delete {_uid::%loop-index%}
		#
		if {_by} != "*":
			loop {_uid::*}:
				element "author:%loop-value%" from cached json "van_album_plus" do not contain "%{_by}%"
				delete {_uid::%loop-index%}
		#
		if size of {_sea::*} != 0:
			loop {_uid::*}:
				delete {_get-a::*}
				set {_get-a::*} to elements "name:%loop-value%[]" from cached json "van_album_plus"
				"%join {_get-a::*} with " "% " do not contain {_sea::*}
				delete {_uid::%loop-index%}
		
		#
		set raw expr-1 to {_uid::*}
		continue
		











skitch command search [<text>]:
	prefixes: -
	trigger:
		cooldown of 5 to event-livechannel
		if (arg-1 ? " ") = " ":
			twitch reply with "Tell me a song and I'll look it up in Muse Dash: _search [song name]"
			stop
		
		#ID
		if see-json "van_album_plus" have key "author:%arg-1%" is true:
			add arg-1 to {_uids::*}
			set {_tra} to music {_uids::*} of album "van_album" from streamer event-livechannel with length of 13
			set {_tra} to "[##%arg-1% %{_tra}%]"
			twitch reply with " ──────────────────────────────── %{_tra}%"
			stop
		#SEARCH SYSTEM
		if arg-1 is set:
			music-filter arg-1 to {_bpm::*} {_dif::*} {_des} {_by} {_search} if {_uids::1} is not set
			index-vanilla in {_uids::*} for {_bpm::*} {_dif::*} {_des} {_by} {_search}
		#OUTPUT
		if size of {_uids::*} > 0:
			set {_tra::*} to music {_uids::*} of album "van_album" from streamer event-livechannel with length of 13
			add "✏️%first 6 characters of {_des}%" to {_filters::*} if {_des} != "*"
			add "⭐%{_dif::1}%->%{_dif::2}%" to {_filters::*} if {_dif::1} != "*"
			set {_all} to "and %size of {_uids::*} - 5% more!" if size of {_uids::*} > 5
			add "⏳%{_bpm::1}%->%{_bpm::2}%" to {_filters::*} if {_bpm::1} != "*"
			add "🎼%first 6 characters of {_by}%" to {_filters::*} if {_by} != "*"
			loop {_tra::*}:
				set {_tra::%loop-index%} to "[%loop-value%]"
			twitch reply with "%join ({_filters::*} ? "") with " "% ──────────────────────────────── %{_tra::1} ? ""% %{_tra::2} ? ""% %{_tra::3} ? ""% %{_tra::4} ? ""% %{_tra::5} ? ""% %{_all} ? ""%"			
		
		else:
			if chance of 20%:
				twitch reply with "[No results available...] Try other arguments: -search by:LeaF"
			else if chance of 20%:
				twitch reply with "[No results available...] Try other arguments: -search bpm:1-1015"
			else if chance of 20%:
				twitch reply with "[No results available...] Try other arguments: -search des:Howard_Y"
			else if chance of 20%:
				twitch reply with "[No results available...] Try other arguments: -search lvl:11-12"
			else:
				twitch reply with "[No results available...] Try other arguments: -search by:Camellia lvl:8-12"
